### ISSUE TITLE
input

### ISSUE THREAD

**Issue by EUNYUSEO** [shleecloud/Culturian#20]
### ISSUE
* Group:  `client`
* Type: `feature`, `design`
* Detail: fix actions from client redux

### TODO
1. [ ]  로그인창 레이아웃 짜기
2. [ ]  버튼 애니메이션 설정
3. [ ]  mypage 페이지에 상태 props로 넘겨주기

### Estimated time
Pick one
